[package]
name = "exlc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
anyhow = "1"
regex = "1"
which = "6"
duct = "0.13"
path-absolutize = "3"
