name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Install aarch64 gcc (for cross link) if needed
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
        working-directory: tools/exlc
      - name: Package
        run: |
          set -e
          mkdir -p dist
          BIN=exlc
          VER=${GITHUB_REF_NAME}
          TGT=${{ matrix.target }}
          SRC=tools/exlc/target/${TGT}/release/${BIN}
          cp "${SRC}" ./exlc
          tar -czf "dist/${BIN}-${VER}-${TGT}.tar.gz" exlc LICENSE README.md
          rm exlc
      - name: SHA256SUMS
        run: |
          cd dist
          sha256sum * > SHA256SUMS.txt
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-13
            target: x86_64-apple-darwin
          - os: macos-14
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
        working-directory: tools/exlc
      - name: Package
        run: |
          set -e
          mkdir -p dist
          BIN=exlc
          VER=${GITHUB_REF_NAME}
          TGT=${{ matrix.target }}
          SRC=tools/exlc/target/${TGT}/release/${BIN}
          cp "${SRC}" ./exlc
          gtar -czf "dist/${BIN}-${VER}-${TGT}.tar.gz" exlc LICENSE README.md || tar -czf "dist/${BIN}-${VER}-${TGT}.tar.gz" exlc LICENSE README.md
          rm exlc
      - name: SHA256SUMS
        run: |
          cd dist
          shasum -a 256 * > SHA256SUMS.txt
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
